=== VarnMeutch/RPG-EMA/core/assets/Dialogs/Rule.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT npc (Line)+ >
        <!ATTLIST npc name CDATA #REQUIRED>

        <!ELEMENT Line (text*,options*) >
        <!ATTLIST Line id ID #REQUIRED>


        <!ELEMENT options (option)+ >

        <!ELEMENT option (#PCDATA) >
        <!ATTLIST option action CDATA #REQUIRED>


        <!ELEMENT text (#PCDATA) >

=== VarnMeutch/RPG-EMA/core/assets/Dialogs/Peter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE npc SYSTEM "Rule.dtd">

		<npc name = "Peter">
			<Line id = "000">
				<text name = "Marchand" > Bienvenu aventurier ! Que venez-vous faire ici ? </text>
				<options>
					<option action = "002">Qu'avez-vous Ã  vendre ?</option>
					<option action = "001">Au revoir.</option>
				</options>
			</Line>
			<Line id="001">
				<text>Au revoir! Revenez vite !</text>
			</Line>
			<Line id="002">
				<text> Regardez donc !</text>
			</Line>
		</npc>
